//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aNyoNe.GetInfoFrom12306.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("aNyoNe.GetInfoFrom12306.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _0 {
            get {
                object obj = ResourceManager.GetObject("_0", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dynamic.12306.cn.
        /// </summary>
        internal static string domain {
            get {
                return ResourceManager.GetString("domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.12306.cn/mormhweb/zxdt/tlxw_tip.html.
        /// </summary>
        internal static string mormhweb_zxdt {
            get {
                return ResourceManager.GetString("mormhweb_zxdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/confirmPassenger/checkOrderInfo.
        /// </summary>
        internal static string otn_checkOrderInfo {
            get {
                return ResourceManager.GetString("otn_checkOrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/passcodeNew/checkRandCodeAnsyn.
        /// </summary>
        internal static string otn_checkRandCodeAsync {
            get {
                return ResourceManager.GetString("otn_checkRandCodeAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/confirmPassenger/confirmSingleForQueue.
        /// </summary>
        internal static string otn_confirmSingleForQueue {
            get {
                return ResourceManager.GetString("otn_confirmSingleForQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/confirmPassenger/confirmSingleForQueueAsys.
        /// </summary>
        internal static string otn_confirmSingleForQueueAsync {
            get {
                return ResourceManager.GetString("otn_confirmSingleForQueueAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/czxx/queryByTrainNo?.
        /// </summary>
        internal static string otn_czxxQueryByTrainNo {
            get {
                return ResourceManager.GetString("otn_czxxQueryByTrainNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/queryOrder/initNoComplete.
        /// </summary>
        internal static string otn_editMemberAction_initEdit {
            get {
                return ResourceManager.GetString("otn_editMemberAction_initEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/passcodeNew/getPassCodeNew?module=passenger&amp;rand=randp.
        /// </summary>
        internal static string otn_getPassCodeNew {
            get {
                return ResourceManager.GetString("otn_getPassCodeNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/passcodeNew/getPassCodeNew.do?.
        /// </summary>
        internal static string otn_getPassCodeNewAsync {
            get {
                return ResourceManager.GetString("otn_getPassCodeNewAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/confirmPassenger/getPassengerDTOs.
        /// </summary>
        internal static string otn_GetPassengerDTOs {
            get {
                return ResourceManager.GetString("otn_GetPassengerDTOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/confirmPassenger/getQueueCount.
        /// </summary>
        internal static string otn_getQueueCount {
            get {
                return ResourceManager.GetString("otn_getQueueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/confirmPassenger/getQueueCountAsync.
        /// </summary>
        internal static string otn_getQueueCountAsync {
            get {
                return ResourceManager.GetString("otn_getQueueCountAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/index/init.
        /// </summary>
        internal static string otn_indexInit {
            get {
                return ResourceManager.GetString("otn_indexInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/confirmPassenger/initDc.
        /// </summary>
        internal static string otn_initDc {
            get {
                return ResourceManager.GetString("otn_initDc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/index/initMy12306.
        /// </summary>
        internal static string otn_initMy12306 {
            get {
                return ResourceManager.GetString("otn_initMy12306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/queryOrder/initNoComplete.
        /// </summary>
        internal static string otn_initNoComplete {
            get {
                return ResourceManager.GetString("otn_initNoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/lcxxcx/init.
        /// </summary>
        internal static string otn_lcxxcxInit {
            get {
                return ResourceManager.GetString("otn_lcxxcxInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/lcxxcx/query?.
        /// </summary>
        internal static string otn_lcxxcxQuery {
            get {
                return ResourceManager.GetString("otn_lcxxcxQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/leftTicket/index.
        /// </summary>
        internal static string otn_leftTicket_index {
            get {
                return ResourceManager.GetString("otn_leftTicket_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/leftTicket/init.
        /// </summary>
        internal static string otn_leftTicket_init {
            get {
                return ResourceManager.GetString("otn_leftTicket_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/leftTicket/queryT?.
        /// </summary>
        internal static string otn_leftTicket_Query {
            get {
                return ResourceManager.GetString("otn_leftTicket_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/login/init.
        /// </summary>
        internal static string otn_loginAction_init {
            get {
                return ResourceManager.GetString("otn_loginAction_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/login/loginAysnSuggest.
        /// </summary>
        internal static string otn_loginAction_login {
            get {
                return ResourceManager.GetString("otn_loginAction_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/login/userLogin.
        /// </summary>
        internal static string otn_loginCheck {
            get {
                return ResourceManager.GetString("otn_loginCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/queryOrder/cancelNoCompleteMyOrder.
        /// </summary>
        internal static string otn_orderAction_cancelMyOrderNotComplete {
            get {
                return ResourceManager.GetString("otn_orderAction_cancelMyOrderNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/queryOrder/initNoComplete#nogo.
        /// </summary>
        internal static string otn_orderAction_cancelMyOrderNotCompleteREF {
            get {
                return ResourceManager.GetString("otn_orderAction_cancelMyOrderNotCompleteREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/passcodeNew/getPassCodeNew.do?module=login&amp;rand=sjrand.
        /// </summary>
        internal static string otn_passCodeAction_sjrand {
            get {
                return ResourceManager.GetString("otn_passCodeAction_sjrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/passengers/add.
        /// </summary>
        internal static string otn_passengersAdd {
            get {
                return ResourceManager.GetString("otn_passengersAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/passengers/addInit.
        /// </summary>
        internal static string otn_passengersAddInit {
            get {
                return ResourceManager.GetString("otn_passengersAddInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/passengers/edit.
        /// </summary>
        internal static string otn_passengersEdit {
            get {
                return ResourceManager.GetString("otn_passengersEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/passengers/show.
        /// </summary>
        internal static string otn_passengersShow {
            get {
                return ResourceManager.GetString("otn_passengersShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/queryOrder/queryMyOrder.
        /// </summary>
        internal static string otn_queryMyOrder {
            get {
                return ResourceManager.GetString("otn_queryMyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/queryOrder/queryMyOrderNoComplete.
        /// </summary>
        internal static string otn_queryMyOrderNoComplete {
            get {
                return ResourceManager.GetString("otn_queryMyOrderNoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/queryOrder/init.
        /// </summary>
        internal static string otn_queryOrderInit {
            get {
                return ResourceManager.GetString("otn_queryOrderInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/confirmPassenger/queryOrderWaitTime?.
        /// </summary>
        internal static string otn_queryOrderWaitTime {
            get {
                return ResourceManager.GetString("otn_queryOrderWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/leftTicket/submitOrderRequest.
        /// </summary>
        internal static string otn_submitOrderRequest {
            get {
                return ResourceManager.GetString("otn_submitOrderRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/confirmPassenger/autoSubmitOrderRequest.
        /// </summary>
        internal static string otn_SubmitOrderRequestAsync {
            get {
                return ResourceManager.GetString("otn_SubmitOrderRequestAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/passengers/show.
        /// </summary>
        internal static string passengerAction_initModifyPassenger {
            get {
                return ResourceManager.GetString("passengerAction_initModifyPassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/passengers/init.
        /// </summary>
        internal static string passengerAction_initUsualPassenger12306 {
            get {
                return ResourceManager.GetString("passengerAction_initUsualPassenger12306", resourceCulture);
            }
        }
    }
}
