//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _12306_Helper.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_12306_Helper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.fishlee.net/Discussion/Advice/51 的本地化字符串。
        /// </summary>
        internal static string Advice {
            get {
                return ResourceManager.GetString("Advice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.fishlee.net/Discussion/Bug/51 的本地化字符串。
        /// </summary>
        internal static string Bug {
            get {
                return ResourceManager.GetString("Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.fishlee.net/Discussion/Common/51 的本地化字符串。
        /// </summary>
        internal static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/order/confirmPassengerAction.do?method=checkOrderInfo 的本地化字符串。
        /// </summary>
        internal static string confirmPassengerAction_checkOrderInfo {
            get {
                return ResourceManager.GetString("confirmPassengerAction_checkOrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/order/confirmPassengerAction.do?method=confirmSingleForQueue 的本地化字符串。
        /// </summary>
        internal static string confirmPassengerAction_confirmSingleForQueue {
            get {
                return ResourceManager.GetString("confirmPassengerAction_confirmSingleForQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/order/confirmPassengerAction.do?method=getpassengerJson 的本地化字符串。
        /// </summary>
        internal static string confirmPassengerAction_getpassengerJson {
            get {
                return ResourceManager.GetString("confirmPassengerAction_getpassengerJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/order/confirmPassengerAction.do?method=getQueueCount 的本地化字符串。
        /// </summary>
        internal static string confirmPassengerAction_getQueueCount {
            get {
                return ResourceManager.GetString("confirmPassengerAction_getQueueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/order/confirmPassengerAction.do?method=init 的本地化字符串。
        /// </summary>
        internal static string confirmPassengerAction_init {
            get {
                return ResourceManager.GetString("confirmPassengerAction_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.fishlee.net/Discussion/Developer/51 的本地化字符串。
        /// </summary>
        internal static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dynamic.12306.cn 的本地化字符串。
        /// </summary>
        internal static string domain {
            get {
                return ResourceManager.GetString("domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/sysuser/editMemberAction.do?method=initEdit 的本地化字符串。
        /// </summary>
        internal static string editMemberAction_initEdit {
            get {
                return ResourceManager.GetString("editMemberAction_initEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.fishlee.net/apps/cn12306/serverip/?method=get 的本地化字符串。
        /// </summary>
        internal static string GetDnsInterface {
            get {
                return ResourceManager.GetString("GetDnsInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.fishlee.net/Apps/Cn12306/IpService/get 的本地化字符串。
        /// </summary>
        internal static string GetDnsInterface1 {
            get {
                return ResourceManager.GetString("GetDnsInterface1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.innke.cn:8080/Play/index.jsp 的本地化字符串。
        /// </summary>
        internal static string GetDnsInterfaceATM {
            get {
                return ResourceManager.GetString("GetDnsInterfaceATM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/passengerAction.do?method=initAddPassenger&amp; 的本地化字符串。
        /// </summary>
        internal static string initAddPassenger {
            get {
                return ResourceManager.GetString("initAddPassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/loginAction.do?method=loginAysnSuggest 的本地化字符串。
        /// </summary>
        internal static string loginAction_AysnSuggest {
            get {
                return ResourceManager.GetString("loginAction_AysnSuggest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/loginAction.do?method=init 的本地化字符串。
        /// </summary>
        internal static string loginAction_init {
            get {
                return ResourceManager.GetString("loginAction_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/loginAction.do?method=login 的本地化字符串。
        /// </summary>
        internal static string loginAction_login {
            get {
                return ResourceManager.GetString("loginAction_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/main.jsp 的本地化字符串。
        /// </summary>
        internal static string main_jsp {
            get {
                return ResourceManager.GetString("main_jsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.fishlee.net/soft/12306_helper/ 的本地化字符串。
        /// </summary>
        internal static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.12306.cn/mormhweb/zxdt/tlxw_tip.html 的本地化字符串。
        /// </summary>
        internal static string mormhweb_zxdt {
            get {
                return ResourceManager.GetString("mormhweb_zxdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/order/myOrderAction.do?method=queryMyOrder 的本地化字符串。
        /// </summary>
        internal static string myOrderAction_queryMyOrder {
            get {
                return ResourceManager.GetString("myOrderAction_queryMyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/order/myOrderAction.do?method=queryMyOrderNotComplete&amp;leftmenu=Y 的本地化字符串。
        /// </summary>
        internal static string myOrderAction_queryMyOrderNotComplete {
            get {
                return ResourceManager.GetString("myOrderAction_queryMyOrderNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/order/myOrderAction.do?method=queryOrderWaitTime&amp;tourFlag=dc 的本地化字符串。
        /// </summary>
        internal static string myOrderAction_queryOrderWaitTime {
            get {
                return ResourceManager.GetString("myOrderAction_queryOrderWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/order/myOrderAction.do?method=init&amp;showMessage=Y 的本地化字符串。
        /// </summary>
        internal static string myOrderAction_showMessage {
            get {
                return ResourceManager.GetString("myOrderAction_showMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/order/orderAction.do?method=cancelMyOrderNotComplete 的本地化字符串。
        /// </summary>
        internal static string orderAction_cancelMyOrderNotComplete {
            get {
                return ResourceManager.GetString("orderAction_cancelMyOrderNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/ 的本地化字符串。
        /// </summary>
        internal static string ostweb {
            get {
                return ResourceManager.GetString("ostweb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/passCodeAction.do?rand=randp 的本地化字符串。
        /// </summary>
        internal static string passCodeAction_randp {
            get {
                return ResourceManager.GetString("passCodeAction_randp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/passCodeAction.do?rand=sjrand 的本地化字符串。
        /// </summary>
        internal static string passCodeAction_sjrand {
            get {
                return ResourceManager.GetString("passCodeAction_sjrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/passengerAction.do?method=getPagePassengerAll 的本地化字符串。
        /// </summary>
        internal static string passengerAction_getPagePassengerAll {
            get {
                return ResourceManager.GetString("passengerAction_getPagePassengerAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/passengerAction.do?method=initModifyPassenger 的本地化字符串。
        /// </summary>
        internal static string passengerAction_initModifyPassenger {
            get {
                return ResourceManager.GetString("passengerAction_initModifyPassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/passengerAction.do?method=initUsualPassenger12306 的本地化字符串。
        /// </summary>
        internal static string passengerAction_initUsualPassenger12306 {
            get {
                return ResourceManager.GetString("passengerAction_initUsualPassenger12306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/passengerAction.do?method=initUsualPassenger12306# 的本地化字符串。
        /// </summary>
        internal static string passengerAction_initUsualPassenger12306All {
            get {
                return ResourceManager.GetString("passengerAction_initUsualPassenger12306All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/passengerAction.do?method=modifyPassenger 的本地化字符串。
        /// </summary>
        internal static string passengerAction_modifyPassenger {
            get {
                return ResourceManager.GetString("passengerAction_modifyPassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/order/querySingleAction.do?method=init 的本地化字符串。
        /// </summary>
        internal static string querySingleAction_init {
            get {
                return ResourceManager.GetString("querySingleAction_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/order/querySingleAction.do?method=queryaTrainStopTimeByTrainNo 的本地化字符串。
        /// </summary>
        internal static string querySingleAction_queryaTrainStopTimeByTrainNo {
            get {
                return ResourceManager.GetString("querySingleAction_queryaTrainStopTimeByTrainNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/order/querySingleAction.do?method=queryLeftTicket 的本地化字符串。
        /// </summary>
        internal static string querySingleAction_queryLeftTicket {
            get {
                return ResourceManager.GetString("querySingleAction_queryLeftTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/order/querySingleAction.do?method=submutOrderRequest 的本地化字符串。
        /// </summary>
        internal static string querySingleAction_submutOrderRequest {
            get {
                return ResourceManager.GetString("querySingleAction_submutOrderRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://dynamic.12306.cn/otsweb/passengerAction.do?method=savePassenger 的本地化字符串。
        /// </summary>
        internal static string savePassenger {
            get {
                return ResourceManager.GetString("savePassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.fishlee.net/Apps/Cn12306/ServerIP?method=reg&amp;ip= 的本地化字符串。
        /// </summary>
        internal static string ServerUpload {
            get {
                return ResourceManager.GetString("ServerUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.fishlee.net/apps/cn12306/ipservice/update 的本地化字符串。
        /// </summary>
        internal static string ServerUploadCloud {
            get {
                return ResourceManager.GetString("ServerUploadCloud", resourceCulture);
            }
        }
    }
}
