//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _12306_Helper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_12306_Helper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0 {
            get {
                object obj = ResourceManager.GetObject("0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dynamic.12306.cn/otsweb/loginAction.do?method=el.
        /// </summary>
        internal static string Action_el {
            get {
                return ResourceManager.GetString("Action_el", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.fishlee.net/Discussion/Advice/51.
        /// </summary>
        internal static string Advice {
            get {
                return ResourceManager.GetString("Advice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dynamic.12306.cn/otsweb/trainQueryAppAction.do?method=kp.
        /// </summary>
        internal static string AppAction {
            get {
                return ResourceManager.GetString("AppAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.alianyone.com/.
        /// </summary>
        internal static string AuthorHomePage {
            get {
                return ResourceManager.GetString("AuthorHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.fishlee.net/Discussion/Bug/51.
        /// </summary>
        internal static string Bug {
            get {
                return ResourceManager.GetString("Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.fishlee.net/Discussion/Common/51.
        /// </summary>
        internal static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dynamic.12306.cn/otsweb/order/confirmPassengerAction.do?method=init.
        /// </summary>
        internal static string confirmPassenger_init {
            get {
                return ResourceManager.GetString("confirmPassenger_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.fishlee.net/Discussion/Developer/51.
        /// </summary>
        internal static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.fishlee.net/apps/cn12306/serverip/?method=get.
        /// </summary>
        internal static string GetDnsInterface {
            get {
                return ResourceManager.GetString("GetDnsInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.fishlee.net/Apps/Cn12306/IpService/getall.
        /// </summary>
        internal static string GetDnsInterface1 {
            get {
                return ResourceManager.GetString("GetDnsInterface1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layerloding {
            get {
                object obj = ResourceManager.GetObject("layerloding", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dynamic.12306.cn/otsweb/loginAction.do?method=init.
        /// </summary>
        internal static string loginAction {
            get {
                return ResourceManager.GetString("loginAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dynamic.12306.cn/otsweb/loginAction.do?method=login.
        /// </summary>
        internal static string loginAction_login {
            get {
                return ResourceManager.GetString("loginAction_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.fishlee.net/soft/12306_helper/.
        /// </summary>
        internal static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dynamic.12306.cn/otsweb/.
        /// </summary>
        internal static string ostweb {
            get {
                return ResourceManager.GetString("ostweb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/queryOrder/initNoComplete.
        /// </summary>
        internal static string otn_initNoComplete {
            get {
                return ResourceManager.GetString("otn_initNoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/leftTicket/init.
        /// </summary>
        internal static string otn_leftTicket_init {
            get {
                return ResourceManager.GetString("otn_leftTicket_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kyfw.12306.cn/otn/login/init.
        /// </summary>
        internal static string otn_login_init {
            get {
                return ResourceManager.GetString("otn_login_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_support {
            get {
                object obj = ResourceManager.GetObject("png_support", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dynamic.12306.cn/otsweb/order/querySingleAction.do?method=init.
        /// </summary>
        internal static string queryAction_init {
            get {
                return ResourceManager.GetString("queryAction_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.fishlee.net/Apps/Cn12306/ServerIP?method=reg&amp;ip=.
        /// </summary>
        internal static string ServerUpload {
            get {
                return ResourceManager.GetString("ServerUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.fishlee.net/apps/cn12306/ipservice/update.
        /// </summary>
        internal static string ServerUploadCloud {
            get {
                return ResourceManager.GetString("ServerUploadCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dynamic.12306.cn/otsweb/js/common/station_name.js.
        /// </summary>
        internal static string station_name {
            get {
                return ResourceManager.GetString("station_name", resourceCulture);
            }
        }
    }
}
